void test_cfa_var_creation() {}
void test_cfa_var_get_id() {}
void test_cfa_var_get_dim_count() {}
void test_cfa_var_get_name() {}
void test_cfa_var_get_type() {}
void test_cfa_var_get_dim() {}
void test_cfa_var_get_dims() {}
void test_cfa_var_get_dim_names() {}
void test_cfa_var_update_dim() {}